#!/bin/bash
sed --in-place -e 's/colorscheme bw_light/colorscheme bw_dark/' $HOME/config/vimrc
sed --in-place -e "s/(load-theme 'bw-light t)/(load-theme 'bw-dark t)/" $HOME/config/emacs.el
sed --in-place -e 's/URxvt\*foreground: fg_light/URxvt\*foreground: fg_dark/' $HOME/config/Xresources
sed --in-place -e 's/URxvt\*background: bg_light/URxvt\*background: bg_dark/' $HOME/config/Xresources
sed --in-place -e 's/export LESS_TERMCAP_us=$(printf "\\e\[33m\")/export LESS_TERMCAP_us=$(printf "\\e\[1;33m\")/' $HOME/config/less_colors
# sed --in-place -e 's/set recolor false/set recolor true/' $HOME/.config/zathura/zathurarc
xrdb -merge $HOME/config/Xresources
