#!/bin/bash
# redirect stdout for the time being
exec 4<&1
exec 1>/dev/null

echo "i3" >&2 && sudo apt-get install --assume-yes i3
echo "i3status" >&2 && sudo apt-get install --assume-yes i3status
echo "rxvt-unicode" >&2 && sudo apt-get install --assume-yes rxvt-unicode
echo "zsh" >&2 && sudo apt-get install --assume-yes zsh
echo "tmux" >&2 && sudo apt-get install --assume-yes tmux
echo "ruby" >&2 && sudo apt-get install --assume-yes ruby
echo "ruby-dev" >&2 && sudo apt-get install --assume-yes ruby-dev
echo "python-dev" >&2 && sudo apt-get install --assume-yes python-dev
echo "exuberant-ctags" >&2 && sudo apt-get install --assume-yes exuberant-ctags
echo "silversearcher-ag" >&2 && sudo apt-get install --assume-yes silversearcher-ag
echo "libx11-dev" >&2 && sudo apt-get install --assume-yes libx11-dev
echo "libncurses5" >&2 && sudo apt-get install --assume-yes libncurses5
echo "libncurses5-dev" >&2 && sudo apt-get install --assume-yes libncurses5-dev
echo "xosd-bin" >&2 && sudo apt-get install --assume-yes xosd-bin
echo "xdotool" >&2 && sudo apt-get install --assume-yes xdotool
echo "xbindkeys" >&2 && sudo apt-get install --assume-yes xbindkeys
echo "xvkbd" >&2 && sudo apt-get install --assume-yes xvkbd
echo "feh" >&2 && sudo apt-get install --assume-yes feh
echo "zathura" >&2 && sudo apt-get install --assume-yes zathura
echo "libasound2-plugin-equal" >&2 && sudo apt-get install --assume-yes libasound2-plugin-equal
echo "mpd" >&2 && sudo apt-get install --assume-yes mpd
echo "ncmpcpp" >&2 && sudo apt-get install --assume-yes ncmpcpp
echo "mplayer" >&2 && sudo apt-get install --assume-yes mplayer
echo "swh-plugins" >&2 && sudo apt-get install --assume-yes swh-plugins
echo "mutt" >&2 && sudo apt-get install --assume-yes mutt
echo "msmtp" >&2 && sudo apt-get install --assume-yes msmtp
echo "sendmail" >&2 && sudo apt-get install --assume-yes sendmail
echo "xfonts-terminus" >&2 && sudo apt-get install --assume-yes xfonts-terminus

sudo update-alternatives --set x-terminal-emulator /usr/bin/urxvt
sudo chsh -s /usr/bin/zsh $USER

test ! -e $HOME/sources && mkdir $HOME/sources
if [ ! -e $HOME/sources/vim ]; then
    git clone https://github.com/vim/vim.git $HOME/sources/vim
fi

command -v vim
if [ ! $? -eq 0 ]; then
    cd $HOME/sources/vim
    rm -f src/auto/config.cache

    ./configure --prefix=/usr \
    --with-x \
    --with-features=big \
    --enable-rubyinterp \
    --enable-pythoninterp \
    --enable-gui=athena \
    --enable-fail-if-missing \
    --disable-darwin \
    --disable-netbeans \
    --enable-cscope \
    --enable-xim \
    --enable-xsmp_interact \
    --disable-sniff \
    --mandir=/usr/share/man \
    > compile_output && make && sudo make install
fi

for f in /etc/fonts/conf.d/10*; do

    # Check if the glob gets expanded to existing files.
    # If not, f here will be exactly the pattern above
    # and the exists test will evaluate to false.
    [ -e "$f" ] && sudo rm /etc/fonts/conf.d/10* || false

    # This is all we needed to know, so we can break after the first iteration
    break
done

if [ -e /etc/fonts/conf.d/70-no-bitmaps.conf ]; then
    sudo rm /etc/fonts/conf.d/70-no-bitmaps.conf
fi

if [ ! -e /etc/fonts/conf.d/70-yes-bitmaps.conf ]; then
    cd /etc/fonts/conf.d
    sudo ln -s ../conf.avail/70-yes-bitmaps.conf .
fi

# restore stdout
exec 1<&4
