#!/bin/bash
echo "coreutils" >&2 && sudo apt-get install --assume-yes coreutils
echo "build-essential" >&2 && sudo apt-get install --assume-yes build-essential
echo "autoconf" >&2 && sudo apt-get install --assume-yes autoconf
echo "xorg-dev" >&2 && sudo apt-get install --assume-yes xorg-dev
echo "openssh-server" >&2 && sudo apt-get install --assume-yes openssh-server
echo "git" >&2 && sudo apt-get install --assume-yes git
echo "i3" >&2 && sudo apt-get install --assume-yes i3
echo "i3status" >&2 && sudo apt-get install --assume-yes i3status
echo "rxvt-unicode-256color" >&2 && sudo apt-get install --assume-yes rxvt-unicode-256color
echo "zsh" >&2 && sudo apt-get install --assume-yes zsh
echo "tmux" >&2 && sudo apt-get install --assume-yes tmux
echo "ruby" >&2 && sudo apt-get install --assume-yes ruby
echo "ruby-dev" >&2 && sudo apt-get install --assume-yes ruby-dev
echo "python-dev" >&2 && sudo apt-get install --assume-yes python-dev
echo "exuberant-ctags" >&2 && sudo apt-get install --assume-yes exuberant-ctags
echo "silversearcher-ag" >&2 && sudo apt-get install --assume-yes silversearcher-ag
echo "libx11-dev" >&2 && sudo apt-get install --assume-yes libx11-dev
echo "libncurses5" >&2 && sudo apt-get install --assume-yes libncurses5
echo "libncurses5-dev" >&2 && sudo apt-get install --assume-yes libncurses5-dev
echo "xosd-bin" >&2 && sudo apt-get install --assume-yes xosd-bin
echo "xbindkeys" >&2 && sudo apt-get install --assume-yes xbindkeys
echo "xvkbd" >&2 && sudo apt-get install --assume-yes xvkbd
echo "feh" >&2 && sudo apt-get install --assume-yes feh
echo "zathura" >&2 && sudo apt-get install --assume-yes zathura
echo "xfonts-terminus" >&2 && sudo apt-get install --assume-yes xfonts-terminus
echo "mpd" >&2 && sudo apt-get install --assume-yes mpd
echo "ncmpcpp" >&2 && sudo apt-get install --assume-yes ncmpcpp
echo "xutils-dev" >&2 && sudo apt-get install --assume-yes xutils-dev
echo "apt-file" >&2 && sudo apt-get install --assume-yes apt-file
echo "xbattbar" >&2 && sudo apt-get install --assume-yes xbattbar
echo "xutils-dev" >&2 && sudo apt-get install --assume-yes xutils-dev
echo "libtiff5-dev" >&2 && sudo apt-get install --assume-yes libtiff5-dev
echo "libjpeg-dev" >&2 && sudo apt-get install --assume-yes libjpeg-dev
echo "libgif-dev" >&2 && sudo apt-get install --assume-yes libgif-dev
echo "libgnutls-dev" >&2 && sudo apt-get install --assume-yes libgnutls-dev
echo "readline-common" >&2 && sudo apt-get install --assume-yes readline-common
echo "libreadline-dev" >&2 && sudo apt-get install --assume-yes libreadline-dev
echo "rlwrap" >&2 && sudo apt-get install --assume-yes rlwrap
echo "redshift" >&2 && sudo apt-get install --assume-yes redshift
echo "texinfo" >&2 && sudo apt-get install --assume-yes texinfo
echo "fftw-dev" >&2 && sudo apt-get install --assume-yes fftw-dev
echo "swh-plugins" >&2 && sudo apt-get install --assume-yes swh-plugins
echo "libasound2-plugin-equal" >&2 && sudo apt-get install --assume-yes libasound2-plugin-equal
echo "xdotool" >&2 && sudo apt-get install --assume-yes xdotool
echo "mplayer" >&2 && sudo apt-get install --assume-yes mplayer
echo "vlc" >&2 && sudo apt-get install --assume-yes vlc

sudo update-alternatives --set x-terminal-emulator /usr/bin/urxvt
sudo chsh -s /usr/bin/zsh $USER

command -v vim
if [ ! $? -eq 0 ]; then
    test ! -e $HOME/sources && mkdir $HOME/sources
    if [ ! -e $HOME/sources/vim ]; then
        git clone https://github.com/vim/vim.git $HOME/sources/vim
    fi

    cd $HOME/sources/vim
    rm -f src/auto/config.cache

    ./configure --prefix=/usr \
    --with-features=big \
    --enable-rubyinterp \
    --with-ruby-command=/usr/bin/ruby \
    --enable-pythoninterp \
    --with-python-command=/usr/bin/python \
    --enable-fail-if-missing \
    --disable-darwin \
    --with-x=no \
    --enable-gui=no \
    --disable-netbeans \
    --enable-cscope \
    --enable-xim \
    --enable-xsmp_interact \
    --mandir=/usr/share/man \
    > compile_output && make && sudo make install

fi

for f in /etc/fonts/conf.d/10*; do

    # Check if the glob gets expanded to existing files.
    # If not, f here will be exactly the pattern above
    # and the exists test will evaluate to false.
    [ -e "$f" ] && sudo rm /etc/fonts/conf.d/10* || false

    # This is all we needed to know, so we can break after the first iteration
    break
done

command -v emacs
if [ ! $? -eq 0 ]; then
    test ! -e $HOME/sources && mkdir $HOME/sources
    if [ ! -e $HOME/sources/emacs ]; then
        git clone https://github.com/emacs-mirror/emacs.git $HOME/sources/emacs
    fi

    cd $HOME/sources/emacs

    ./autogen.sh && ./configure --with-gnutls=no && make && sudo make install
fi

for f in /etc/fonts/conf.d/10*; do

    # Check if the glob gets expanded to existing files.
    # If not, f here will be exactly the pattern above
    # and the exists test will evaluate to false.
    [ -e "$f" ] && sudo rm /etc/fonts/conf.d/10* || false

    # This is all we needed to know, so we can break after the first iteration
    break
done

if [ -e /etc/fonts/conf.d/70-no-bitmaps.conf ]; then
    sudo rm /etc/fonts/conf.d/70-no-bitmaps.conf
fi

if [ ! -e /etc/fonts/conf.d/70-yes-bitmaps.conf ]; then
    cd /etc/fonts/conf.d
    sudo ln -s ../conf.avail/70-yes-bitmaps.conf .
fi
