#!/bin/bash
sed --in-place -e 's/colorscheme bw_dark/colorscheme bw_light/' $HOME/config/vimrc
sed --in-place -e "s/(load-theme 'bw-dark t)/(load-theme 'bw-light t)/" $HOME/config/emacs.el
sed --in-place -e 's/URxvt\*foreground: fg_dark/URxvt\*foreground: fg_light/' $HOME/config/Xresources
sed --in-place -e 's/URxvt\*background: bg_dark/URxvt\*background: bg_light/' $HOME/config/Xresources
sed --in-place -e 's/export LESS_TERMCAP_us=$(printf "\\e\[1;33m\")/export LESS_TERMCAP_us=$(printf "\\e\[33m\")/' $HOME/config/less_colors
# sed --in-place -e 's/set recolor true/set recolor false/' $HOME/.config/zathura/zathurarc
xrdb -merge $HOME/config/Xresources
