#!/usr/bin/env sh
dir=$HOME/config
olddir=$HOME/old_config
files="vimrc emacs inputrc bashrc Xmodmap Xresources xinitrc exrc tmux.conf \
       gitconfig gitignore offlineimaprc zshrc vim emacs.d msmtprc mutt \
       zprofile profile functions light.txt dark.txt theme"

mkdir -p $olddir
for file in $files; do
    mv --backup=numbered $HOME/.$file $olddir 2>/dev/null
    ln -s ./config/$file $HOME/.$file
done

git update-index --skip-worktree theme

if [ -f "$HOME/patches/config_patch" ]; then
    $HOME/patches/config_patch
fi

cd vim/bundle/command-t/ruby/command-t
ruby extconf.rb >/dev/null 2>&1 && make >/dev/null 2>&1
if [ ! $? -eq 0 ]; then
    echo "Failed to setup command-t"
fi
