#!/bin/bash
sudo apt-get install --assume-yes i3 \
i3status \
silversearcher-ag \
xfonts-terminus

# cd /etc/fonts
# cd conf.d
# sudo rm /etc/fonts/conf.d/10*
# sudo rm -rf 70-no-bitmaps.conf
# sudo ln -s ../conf.avail/70-yes-bitmaps.conf .
