#!/usr/bin/env sh
confdir=$HOME/config
olddir=$HOME/old_config
files="Xmodmap"

mkdir -p $olddir
for file in $files; do
    mv --backup=numbered $HOME/.$file $olddir 2>/dev/null
    ln -s ./config/$file $HOME/.$file
done

command -v apt-get >/dev/null 2>&1 && $confdir/simplified_install_packages

test ! -e $HOME/.i3 && mkdir $HOME/.i3
test -e $HOME/.i3/config && mv --backup=numbered $HOME/.i3/config $olddir
ln -s $confdir/i3config $HOME/.i3/config
