#!/usr/bin/env sh
dir=$HOME/config
olddir=$HOME/old_config
files="vimrc emacs inputrc bashrc Xmodmap Xresources xinitrc exrc tmux.conf \
       gitconfig gitignore offlineimaprc zshrc vim emacs.d msmtprc mutt \
       zprofile profile functions light.txt dark.txt theme"

mkdir -p $olddir
for file in $files; do
    mv --backup=numbered $HOME/.$file $olddir 2>/dev/null
    ln -s ./config/$file $HOME/.$file
done

git update-index --skip-worktree theme
